### ISSUE TITLE
Find good consistent React CSS styles

### ISSUE THREAD

**Issue by ansonmiu0214** [cockatoos/sprint-board#5]

**Comment by neshang** [comment]
@ansonmiu0214 Angular is in a similar situation I think. I found some free themes for both angular and react in Creative Tim: https://www.creative-tim.com. 

The style I am looking for is similar to https://www.creative-tim.com/product/black-dashboard-react#
The dark mode and bright blue looks really sleek.
The theme has a free version but only with very limited components. Also I think it might not be that hard for us to achieve similar effect using Angular material or react material UI. The reason why it looks cool is more on the choice of the colour palette.

**Comment by neshang** [comment]
also although we could use some pre-built components, we could also build the MVP using material component first, and create a separate ticket on generating a theme for the whole app.

**Comment by neshang** [comment]
I am quite indecisive when it comes to choosing between two similar framework. As I am getting a bit busy for my rotation recently, I might actually prefer Angular now (so sorry for keep changing!). Should we just make a final decision on using Angular? Otherwise I feel I will just swing between the two choices. 😂

**Comment by ansonmiu0214** [comment]
@neshang let's do Angular then :) I'll change the repo
