### ISSUE TITLE
Wireframes - main component for recording and comparing

### ISSUE THREAD

**Issue by ansonmiu0214** [cockatoos/sprint-board#8]

**Comment by ansonmiu0214** [comment]
WIP: https://docs.google.com/drawings/d/15bHdbEXLA337V134x-aYTo0tzxLhiE9Pjvi5-wGzjak/edit?usp=sharing

**Comment by neshang** [comment]
The mockup looks good!! Separating out the target phrase makes much more sense. I was thinking just highlighting the target phrase in the original text, but your design is definitely much more user-friendly.

There are two small things:

1. would it be better to separate the original text and (target phrase + user input + buttons) into two columns. So even if the article is really long, we can keep everything in one section without much scrolling.

2. having a running number is good, but it might be a bit distracting because it changes quite frequently. Would it make sense to show an overall score together with the accent score in the end? But ofc we can keep it for now and revisit the user experience later.

**Comment by ansonmiu0214** [comment]
@neshang Thanks!

1. I think the two-column view a good idea for desktops/laptops with medium-large screens. For a mobile view the layout can be adapted to a one-column view. But as far as the MVP is concerned we can stick to designing for desktops/laptops using the 2 columns.

2. Yes, a running number can give some real-time feedback to the user, by could also be confusing. Showing the overall score at the end sounds good as well.
